vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
            attachments:
                uri_prefix: /images/attachments
                upload_destination: '%kernel.project_dir%/public/uploads/images/attachments'
